
import type { Hotel } from './types';

export const MOCK_HOTELS: Hotel[] = [
  // Pokhara
  {
    hotel_id: 101,
    hotel_name: 'Pokhara Grandeur',
    location: 'Pokhara',
    price_per_night: 150,
    room_type: 'Deluxe',
    availability: true,
    image_url: 'https://picsum.photos/seed/pokhara1/400/300',
    amenities: ['Free WiFi', 'Pool', 'Spa', 'Mountain View'],
  },
  {
    hotel_id: 102,
    hotel_name: 'Lakeside Retreat',
    location: 'Pokhara',
    price_per_night: 250,
    room_type: 'Suite',
    availability: true,
    image_url: 'https://picsum.photos/seed/lakeside/400/300',
    amenities: ['Private Balcony', 'Lake View', 'Restaurant', 'Free WiFi'],
  },
  {
    hotel_id: 103,
    hotel_name: 'Peaceful Pagoda Inn',
    location: 'Pokhara',
    price_per_night: 90,
    room_type: 'Standard',
    availability: true,
    image_url: 'https://picsum.photos/seed/pagoda/400/300',
    amenities: ['Garden', 'Free WiFi', 'Yoga Hall'],
  },
  // Kathmandu
  {
    hotel_id: 201,
    hotel_name: 'Kathmandu Courtyard',
    location: 'Kathmandu',
    price_per_night: 120,
    room_type: 'Standard',
    availability: true,
    image_url: 'https://picsum.photos/seed/kathmandu1/400/300',
    amenities: ['Free WiFi', 'City Center', 'Restaurant', 'Gym'],
  },
  {
    hotel_id: 202,
    hotel_name: 'Himalayan Heights',
    location: 'Kathmandu',
    price_per_night: 220,
    room_type: 'Suite',
    availability: false, // Intentionally unavailable
    image_url: 'https://picsum.photos/seed/himalayan/400/300',
    amenities: ['Rooftop Bar', 'Panoramic Views', 'Spa', 'Airport Shuttle'],
  },
  {
    hotel_id: 203,
    hotel_name: 'Thamel Boutique Hotel',
    location: 'Kathmandu',
    price_per_night: 160,
    room_type: 'Deluxe',
    availability: true,
    image_url: 'https://picsum.photos/seed/thamel/400/300',
    amenities: ['Art Gallery', 'Cafe', 'Free WiFi', 'Tour Desk'],
  },
  // Chitwan
  {
    hotel_id: 301,
    hotel_name: 'Chitwan Jungle Lodge',
    location: 'Chitwan',
    price_per_night: 180,
    room_type: 'Deluxe',
    availability: true,
    image_url: 'https://picsum.photos/seed/chitwan1/400/300',
    amenities: ['Jungle Safari', 'Pool', 'All-inclusive', 'Nature Guide'],
  },
  {
    hotel_id: 302,
    hotel_name: 'Rapti River Resort',
    location: 'Chitwan',
    price_per_night: 280,
    room_type: 'Suite',
    availability: true,
    image_url: 'https://picsum.photos/seed/rapti/400/300',
    amenities: ['River View', 'Canoeing', 'Wildlife Tours', 'Spa'],
  },
  // Butwal
  {
    hotel_id: 401,
    hotel_name: 'Butwal Business Inn',
    location: 'Butwal',
    price_per_night: 80,
    room_type: 'Standard',
    availability: true,
    image_url: 'https://picsum.photos/seed/butwal1/400/300',
    amenities: ['Conference Hall', 'Free WiFi', 'Restaurant'],
  },
  {
    hotel_id: 402,
    hotel_name: 'The Siddhartha',
    location: 'Butwal',
    price_per_night: 130,
    room_type: 'Deluxe',
    availability: true,
    image_url: 'https://picsum.photos/seed/siddhartha/400/300',
    amenities: ['Pool', 'Gym', 'Fine Dining', 'Free WiFi'],
  },
];
